name: air_paradis

services:
  api:
    build: 
      context: ./fastapi
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./fastapi/model:/app/model
    restart: unless-stopped
    env_file:
      - ./fastapi/.env
    networks:
      - air_paradis_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - api
    env_file:
      - ./frontend/.env
    environment:
      - NEXT_PUBLIC_API_URL=http://api:8000
    networks:
      - air_paradis_network

networks:
  air_paradis_network:
    driver: bridge